### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sha-265** [bither/bither-ios#18]

**Comment by servicedesignthinking** [comment]
Hallo
I have send 1 Bitcoin plus 0,0001 Fee to 
an Bither-Address, like 16jar...
but I never received it at my bither wallet.
How could I get that 1 Bitcoin back or how 
can I get it in my wallet.
I made one change after I waited 1 day.
I opened the wallet with the the Adress "16jar..."
and went to settings (...) and made click on
"Request New Address". There didnt came
any question, if I like to do it, and since then
I habe a new address, but still can see the
old address by clicking on "Old address".
But my main-question is, why the Bitcoins
are not in my bither-wallet?
I asked bitcoin.de and Coinbase.com, and both
said the transaction was fine.
Best Regards
Torsten Stapelkamp

**Comment by bithernet** [comment]
@servicedesignthinking Have you synced to the newest block? Bither is a decentralized SPV wallet, and it needs to sync with the other nodes in the bitcoin network.

You can find out the syncing status in "Advanced Options"/"Network Monitoring"

**Comment by servicedesignthinking** [comment]
@bithernet
Syncing is the keyword...  ;-)
It was my mistake.
I checked on, only to sync by WiFi.
And I was driving all the time with switched off WiFi at iPhone.
Sorry for asking.
Now everything is fine.
Thanks a lot.
cheers
Torsten

**Comment by bithernet** [comment]
@servicedesignthinking you are welcome!

**Comment by ddimme** [comment]
Hi I have a big problem with bither android app. After I use bither to claim BTW from my Bitcoin Electrum wallet my Bitcoin where transfered to another Bitcoin address. I use your function "Import Private Key" and a Bitpie BTW address. Now my Bitcoin were loss by this Bither function. Here you can see the transfer data on blockchain.info:
https://blockchain.info/tx/9f77cc5f6ec0a2ddf525a48c994e48e9409927d52a0d7591868e629c277a447f

And days later my Bitcoin are transfered to another Bitcoin address and finally on another address:
https://blockchain.info/address/34xsiBXp3wSGXgVTDtmnkatZ2LbJ3gFMVW
https://blockchain.info/address/1F7zgAQ3D41KigYGuVmq7zuRJEbyLYsjN8

I feel so sad, my Bitcoin were stolen by a Bither transaction to claim BTW! I want my Bitcoin back!!!
How can this happen? What have you done?
