### ISSUE TITLE
Keyboards

### ISSUE THREAD

**Issue by zzaappedd** [bither/bither-ios#19]
First, a minor thing:
I noticed that with my optional keyboard [ TouchPal ] it remembered and suggested one word after another of the 12 words I had entered previously.  The input should switch to a simple keyboard without any suggestions/predictive features.

Preferences / Advance Options, should be Advance>d< Options.

Then I have a problem understanding usage:

I generate a mnemonic phrase which should help me recover my keys.  Bither generates word1-word2-.-.-word12 separated using dashes.  Most other programs use spaces for the phrase.  This is confusing at the time of recovery.  Then I reinstalled Bither (now there's no wallet in it) to simulate phone loss and tried to recover my wallet with the phrase created earlier.  I Assume it should be at Advance;) Options and try HDM recover, but it's not there since I havent created a wallet yet.  So where should I enter my passphrase to recover my key sequence?  Tried Import Private Key from text (but think to myself: it isn't a key it's a wallet!) still try and it doesn't work.  What's the sequence to recover a wallet from the written mnemonic word sequence?

I hope I can understand it before I commit to it.
Thank you for such nice software!

**Comment by songchenwen** [comment]
Thank you for trying to use Bither. :smile:

For the optional keyboard thing, only when the input field is set to password type, the iOS runtime will limit the keyboard to system default keyboard. Otherwise it will use the keyboard user chooses, and Bither has no way to know which keyboard the user chooses. But with password type set, the letters you type will hide behind dots in the text field. Do you think this is a good approach, or should we just put a label here to suggest the user to manually switch to the system default keyboard?

Advance>d< Options has already been fixed in 456dda2 . The new iOS version with this fix is waiting for the review of App Store now.

The dash separator is just used to make the words more readable. There's no difference from space separated phrases.

`From HD Account Phrase` is at `Advanced Options` -> `Import Private Key`. This function can only be accessed at hot mode, when you have no existing HD Account in Bither.

We will continue improving Bither. All your advises will be of great help to us.

**Comment by zzaappedd** [comment]
I've never used github and don't know if this is the right place or format to discuss this.

As for the keyboard issue, since it should only be used for reinstating a wallet, I rather see the letters and deal with the consequences of my keyboard storing the info (many keyboards send the data to their servers where there could be a script matching 12 word sequences to the 2k word list to then swipe all coins)

For the wallet recovery, I tried 3 times and could not get Import Private Key to recover wallet.  Everytime from the start (I chose hot wallet and no password/pin/or wallet had been created).
When entering QR& pass it said 'password wrong' 
When trying the text option 'Not match private key format'  [did both spaces and '-' dashes].
Suggestions?
Thanks

**Comment by songchenwen** [comment]
For the wallet recovery, when you pressed the `Import Private Key` button, do you see what I see as below?

![img_7843](https://cloud.githubusercontent.com/assets/6240753/7791159/e2b53044-02cd-11e5-8317-22e1828786b0.PNG)

Choose `From HD Account Phrase` here, will present you a special view to enter your phrase.

**Comment by zzaappedd** [comment]
I had seen the import private key screen with the HD options at some time a few days ago, but is not coming up now.  Now I only see the 2 lines: 'from bither..' and 'from private'.  I've deleted the app and tried again but nothing not when there's a genereted wallet nor without it.  I'm in v1.3.4  Can you tell me how to completely delete the app and data?  I go into iexplore and delete de app's folder and it seems to reset the app since it starts from the cold/hot wallet choice screen; which doesn't happen when I just delete and reinstall the app thru appstore.  But maybe it's not fully reset with iexplores option. sorry to waste your time... thanks

**Comment by zzaappedd** [comment]
http://imgur.com/xTlfkOI

**Comment by songchenwen** [comment]
I just uninstalled Bither from home screen and reinstalled it from App Store, and I can see the HD Account options now. 

I think your problem may be due to some iOS issues.

Could you tell me which iOS version are you on? Have jailbroken your device?

**Comment by zzaappedd** [comment]
My phone:
iphone 5 -  ios 8.1.2 - Jailbroken.

Another iphone: 
iphone 4s - ios 8.1.3 - non-Jailbroken

Worked!

Sorry to bother you with my infected ;) phone. I know I shouldn't be using it to handle my coins because any other impure app could grab my info and swipe all my coins.   
Good Luck

**Comment by songchenwen** [comment]
I saw you had posted the screenshot of your HD Account Seed QR Code. I strongly suggest you stop using this seed any more. Because anyone who has seen this screenshot may recover you HD Account. I will edit your comment and delete the screenshot.

Any further advices are welcome. Just open a new issue here.

**Comment by zzaappedd** [comment]
Thanks for the help.  No problem, I've been spending Seed in vain (punishable in some religions! :), can't trust this phone anyway.
